---
image: prowlarr
version: 0.1.0
name: Prowlarr
description: "[Prowlarr](https://github.com/Prowlarr/Prowlarr) is a indexer manager/proxy built on the popular arr .net/reactjs base stack to integrate with your various PVR apps. Prowlarr supports both Torrent Trackers and Usenet Indexers. It integrates seamlessly with Sonarr, Radarr, Lidarr, and Readarr offering complete management of your indexers with no per app Indexer setup required (we do it all)."
ext_release: v1.8.6.3946
arch:
  - aarch64
  - x86_64
  - armv7
